# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [9]:
# Create a 1-dimensional NumPy array using np.array()
np1 = np.array([1,2,3])
# Create a 2-dimensional NumPy array using np.array()
np2 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
# Create a 3-dimensional Numpy array using np.array()
np3 = np.array([[[1,2,3],
        [4,5,6],
        [7,8,9]],
        [[1,2,3],
        [4,5,6],
        [7,8,9]]])



In [10]:
np1

array([1, 2, 3])

In [11]:
np2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [13]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
np1.shape, np1.ndim, np1.dtype, np1.size

((3,), 1, dtype('int32'), 3)

In [15]:
# Attributes of 2-dimensional array
np2.shape, np2.ndim, np2.dtype, np2.size

((3, 3), 2, dtype('int32'), 9)

In [16]:
# Attributes of 3-dimensional array
np3.shape, np3.ndim, np3.dtype, np3.size

((2, 3, 3), 3, dtype('int32'), 18)

In [26]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(np2)
# print(df.to_string(index=False))
#print(df.to_string())
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [28]:
# Create an array of shape (10, 2) with only ones
np_array_ones = np.ones(shape = (10,2))
np_array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
# Create an array of shape (7, 2, 3) of only zeros
np_array_zeros = np.zeros(shape = (7,2,3))
np_array_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
# Create an array within a range of 0 and 100 with step 3
np_range = np.arange(0,100,3)
np_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [33]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np_random = np.random.randint(0,10,size=(7,2))
np_random

array([[7, 7],
       [2, 7],
       [6, 6],
       [6, 7],
       [1, 6],
       [9, 7],
       [3, 1]])

In [36]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np_random_floats = np.random.rand(3,5)
np_random_floats

array([[0.66647443, 0.19956075, 0.59610057, 0.61309502, 0.54036258],
       [0.24239728, 0.82294494, 0.47390513, 0.27646015, 0.19103206],
       [0.95865121, 0.13525988, 0.34339787, 0.07020661, 0.93166653]])

In [39]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np_random_2 = np.random.randint(0,10,size=(4,6))
np_random_2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [48]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np_random_3 = np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(np_random_3).size
np_random_3

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3],
       [1, 8, 3, 3, 1, 5, 7]])

In [49]:
# Find the 0'th index of the latest array you created
np_random_3[0]

array([2, 5, 8, 9, 9, 1, 9])

In [50]:
# Get the first 2 rows of latest array you created
np_random_3[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [51]:
# Get the first 2 values of the first 2 rows of the latest array
np_random_3[:2,:2]

array([[2, 5],
       [7, 9]])

In [54]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
my_array_nums = np.random.randint(0,10, size = (3,5))
my_array_ones = np.ones(shape = (3,5))
my_array_nums, my_array_ones

(array([[3, 3, 4, 6, 6],
        [3, 6, 2, 5, 1],
        [9, 8, 4, 5, 3]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [55]:
# Add the two arrays together
my_array_nums + my_array_ones

array([[ 4.,  4.,  5.,  7.,  7.],
       [ 4.,  7.,  3.,  6.,  2.],
       [10.,  9.,  5.,  6.,  4.]])

In [58]:
# Create another array of ones of shape (5, 3)
my_array_ones2 = np.ones(shape = (5,3))
my_array_ones2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
# Try add the array of ones and the other most recent array together
my_array_ones + my_array_ones2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

The dimensions are not equal or equal to one - you could transpose the data.

In [60]:
# Create another array of ones of shape (3, 5)
another_ones = np.ones(shape=(3,5))
another_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
# Subtract the new array of ones from the other most recent array
my_array_ones - another_ones

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
# Multiply the ones array with the latest array
my_array_ones * another_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
# Take the latest array to the power of 2 using '**'
another_ones ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
# Do the same thing with np.square()
np.square(another_ones)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
# Find the mean of the latest array using np.mean()
my_array_nums.mean()

4.533333333333333

In [66]:
# Find the maximum of the latest array using np.max()
my_array_nums.max()

9

In [67]:
# Find the minimum of the latest array using np.min()
my_array_nums.min()

1

In [68]:
# Find the standard deviation of the latest array
my_array_nums.std()

2.124983660067897

In [69]:
# Find the variance of the latest array
my_array_nums.var()

4.515555555555555

In [72]:
# Reshape the latest array to (3, 5, 1)
my_array_nums.shape
my_array_nums.reshape((3,5,1))

array([[[3],
        [3],
        [4],
        [6],
        [6]],

       [[3],
        [6],
        [2],
        [5],
        [1]],

       [[9],
        [8],
        [4],
        [5],
        [3]]])

In [73]:
# Transpose the latest array
my_array_nums.T

array([[3, 3, 9],
       [3, 6, 8],
       [4, 2, 4],
       [6, 5, 5],
       [6, 1, 3]])

What does the transpose do?

In [76]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np_array1 = np.random.randint(0,10,size = (3,3))
np_array2 = np.random.randint(0,10,size = (3,2))
np_array1,np_array2

(array([[4, 0, 2],
        [9, 7, 5],
        [7, 8, 3]]),
 array([[0, 0],
        [9, 3],
        [6, 1]]))

In [77]:
# Perform a dot product on the two newest arrays you created
np.dot(np_array1,np_array2)

array([[12,  2],
       [93, 26],
       [90, 27]])

In [78]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np_array1 = np.random.randint(0,10,size = (4,3))
np_array2 = np.random.randint(0,10,size = (4,3))
np_array1,np_array2

(array([[2, 0, 4],
        [0, 7, 0],
        [0, 1, 1],
        [5, 6, 4]]),
 array([[0, 0, 2],
        [1, 4, 9],
        [5, 6, 3],
        [6, 7, 0]]))

In [79]:
# Perform a dot product on the two newest arrays you created
np.dot(np_array1,np_array2.T)

array([[ 8, 38, 22, 12],
       [ 0, 28, 42, 49],
       [ 2, 13,  9,  7],
       [ 8, 65, 73, 72]])

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [80]:
# Compare the two arrays with '>'
np_array1 > np_array2

array([[ True, False,  True],
       [False,  True, False],
       [False, False, False],
       [False, False,  True]])

What happens when you compare the arrays with `>`?

In [81]:
# Compare the two arrays with '>='
np_array1 >= np_array2

array([[ True,  True,  True],
       [False,  True, False],
       [False, False, False],
       [False, False,  True]])

In [82]:
# Find which elements of the first array are greater than 7
np_array1 > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [83]:
# Which parts of each array are equal? (try using '==')
np_array1 == np_array2

array([[False,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [87]:
# Sort one of the arrays you just created in ascending order
np.sort(np_array1)
np_array1

array([[2, 0, 4],
       [0, 7, 0],
       [0, 1, 1],
       [5, 6, 4]])

In [88]:
# Sort the indexes of one of the arrays you just created
np.sort(np.argsort(np_array1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [89]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(np_array1)

4

In [90]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(np_array1)

1

In [91]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(np_array1, axis=1)

array([2, 1, 1, 1], dtype=int64)

In [93]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(np_array1, axis=0)
np.argmin(np_array1, axis=-1)

array([1, 0, 0, 2], dtype=int64)

In [96]:
# Create an array of normally distributed random numbers
test_array = np.random.normal(size = (10,10))
test_array.mean()

0.18271915549700882

In [100]:
# Create an array with 10 evenly spaced numbers between 1 and 100
tens = np.arange(0,100,10)
tens

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.